// 2025-11-21 18:32 動作確認OK

/*
 * DATE		: 2024-06-15
 * LASTUPDATE:2025-11-07
 * Author:Takashi Oikawa
 * Function:
*/

//<%--JSPのコメント
//DATE		: 2024-06-15
//LASTUPDATE:2025-11-07
//Author:Takashi Oikawa
//Function:vaaaaa
//--%>


/* USERSテーブル作成SQL */
/*
CREATE TABLE USERS (
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(100) NOT NULL UNIQUE,
PASS VARCHAR(255) NOT NULL,
E_MAIL VARCHAR(100) NOT NULL,                      --email address
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,　　--作成日YYYY-MM-DD HH:MM:SS
UPDATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,     --更新日
DELETED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,    --削除フラグセット日
LAST_LOGIN_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP, --最新アクセス日
DELETD_FLAG VARCHAR(1)  DEFAULT NULL               --削除フラグ　D or NULL
);
*/